### ISSUE TITLE
IR genotypes file for data release

### ISSUE THREAD

**Issue by cclarkson** [malariagen/ag1000g-phase2-data-paper#225]
I think we need to add cyp CNV presence/absence to this table due to figure 6.

**Comment by alimanfoo** [comment]
Hi @cclarkson, how about this for the set of columns to include:

* `ox_code`
* `vgsc_995_gt` - string, VGSC codon 995 genotype, one of "+/+", "+/F", "+/S", "F/F", "S/S", "F/S"
* `vgsc_1570_gt` - string, VGSC codon 1570 genotype
* `vgsc_[...]_gt` - fields giving amino acid genotypes for all other codons we list in the table in the VGSC paper
* `vgsc_kdr_f_gn` - int, number of L995F alleles present (e.g., 1 if heterozygous, 2 if homozygous)
* `vgsc_kdr_s_gn` - int, number of L995S alleles present
* `vgsc_kdr_gn` - int, number of kdr alleles present (either S or F)
* `vgsc_any_kdr` - bool, True if any kdr alleles present
* `cyp6aa1_cn` - float, HMM copy number for window(s) in Cyp6aa1
* `cyp6aa2_cn` - float, HMM copy number for window(s) in Cyp6aa2
* `coeae60_cn` - float, HMM copy number for window(s) in Coeae60
* `cyp[...]_cn` - fields giving HMM copy number for other genes in the Cyp6aa/p cluster
* `cyp6aap_any_cnv` - bool, True if any genes in the Cyp6aa/p cluster have copy number greater than 2, otherwise False
* `gstu4_cn` - float, HMM copy number for window(s) in Gstu4
* `gste6_cn` - float, HMM copy number for window(s) in Gste6
* `gste[...]_cn` - further fields giving HMM copy number for other genes in the Gste cluster
* `gste_any_cnv` - bool, True if any genes in the Gste cluster have copy number greater than 2, otherwise False
* `cyp6m[...]_cn` - fields giving HMM copy number for Cyp6m2, Cyp6m3 and Cyp6m4
* `cyp6m_any_cnv` - bool, True if any genes in Cyp6m gene cluster have copy number greater than 2
* `cyp6z[...]_cn` - fields giving HMM copy number for Cyp6z3, Cyp6z2, Cyp6z1
* `cyp6z_any_cnv` - bool, True if any genes in Cyp6z gene cluster have copy number greater than 2
* `cyp9k1_cn` - float - HMM copy number for window(s) in Cyp9k1
* `cyp9k1_any_cnv` - bool, True if Cyp9k1 copy number greater than 2
* `cyp_any_cnv` - bool, True if any of the Cyp genes listed above have copy number greater than 2
* `ace1_cn` - float, HMM copy number for window(s) in Ace1
* `ace1_any_cnv` - bool, True if Ace1 copy number greater than 2
* `ace1_[...]_gt` - string, genotype for the codon 119 SNP (although using Agam codon numbering)
* `rdl_[...]_gt` - string, genotype for the dieldring target site resistance codon (can't remember off the top of my head)

This is a lot to put together, but I'm thinking it's better to be comprehensive and provide a bit more detail for those who might want to break things down. I.e., for our pyrethroid resistance figure we might just use the `vgsc_any_kdr` and `cyp_any_cnv` fields, but we could also make some more detailed breakdowns. Very happy to discuss.

**Comment by alimanfoo** [comment]
Some other possibly useful fields:

* `cyp6aap_max_cn` - float, max copy number for any genes in the Cyp6aa/p cluster
* `gste_max_cn` - float, max copy number for any genes in the Gste cluster
* `cyp6m_max_cn`
* `cyp6z_max_cn`
* `gste2_119_gt` - string, amino acid genotype for the known DDT-resistance SNP (if I remembered the codon number right)

**Comment by alimanfoo** [comment]
Btw [this paper](https://www.nature.com/articles/s41598-019-45261-5) has some nice ideas for how to visualize frequencies of multiple IR markers. E.g.:

![image](https://user-images.githubusercontent.com/703554/66142834-177c8080-e5fe-11e9-8ad9-10d3e34ecab2.png)

I mention because if we include all the fields suggested above, we have all we need to make some multi pie chart figures, which might not be needed for the current resource paper but might be useful in future. E.g., if we want to present a summary of frequency of vgsc_any_kdr, cyp_any_cnv and gste_any_cnv, we could use 3 pie charts for each population, which would probably be better than trying to combined all variables into a single pie per population. Not suggesting we make that plot now, but thinking ahead to have the necessary data.

**Comment by alimanfoo** [comment]
Hi @EricRLucas, would you be able to create a tab-delimited file, one row per sample, with the following fields based on data from the CNV HMM:

* `ox_code`
* `cyp6aa1_cn` - HMM copy number for Cyp6aa1
* `cyp6p[...]_cn` - fields giving HMM copy number for other genes in the Cyp6aa/p cluster
* `cyp6p_max_cn` - max copy number for any genes in the Cyp6aa/p cluster
* `cyp6p_any_cnv` - True if any genes in the Cyp6aa/p cluster have copy number greater than 2, otherwise False
* `gstu4_cn` - HMM copy number for Gstu4
* `gste[...]_cn` - fields giving HMM copy number for other genes in the Gste cluster
* `gste_max_cn` - max copy number for any genes in the Gste cluster
* `gste_any_cnv` - True if any genes in the Gste cluster have copy number greater than 2, otherwise False
* `cyp6m[...]_cn` - fields giving HMM copy number for Cyp6m2, Cyp6m3 and Cyp6m4
* `cyp6m_max_cn`
* `cyp6m_any_cnv` - True if any genes in Cyp6m gene cluster have copy number greater than 2
* `cyp6z[...]_cn` - fields giving HMM copy number for Cyp6z3, Cyp6z2, Cyp6z1
* `cyp6z_max_cn`
* `cyp6z_any_cnv` - True if any genes in Cyp6z gene cluster have copy number greater than 2
* `cyp9k1_cn` - HMM copy number for Cyp9k1
* `cyp9k1_any_cnv` - True if Cyp9k1 copy number greater than 2
* `cyp_any_cnv` - True if any of the Cyp genes listed above have copy number greater than 2
* `ace1_cn` - HMM copy number for Ace1
* `ace1_any_cnv` - True if Ace1 copy number greater than 2

For the per-gene copy number fields like `cyp6aa1_cn` there is a question how to compute this, given that a gene may be overlapped by multiple windows. One option would be to take the maximum HMM value for the overlapping windows. Another option would be to take the average HMM value from the overlapping windows. I leave it to you to decide what you think is best. 

Hope that makes sense, give me a shout if any questions.

**Comment by EricRLucas** [comment]
No problem. For copy number, I suggest using the mode

**Comment by alimanfoo** [comment]
Thanks @EricRLucas, sounds good.
