### ISSUE TITLE
Add author institutional affiliations to the paper

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#230]

**Comment by cclarkson** [comment]
Hi @alimanfoo,

I'm not sure what a sensible way of doing this is - I might just do it manually?

Are we just copying over the Phase 1 affiliations to start with then getting consortium members to fix?

**Comment by cclarkson** [comment]
@alimanfoo - I've been playing with [cleveref](http://tug.ctan.org/tex-archive/macros/latex/contrib/cleveref/cleveref.pdf), it works great for single affiliation references (multiple references to the same footnote), but for folk with multiple affiliations the in text reference comes out funky. I think this might be due to the formatting line at the top of the document but I haven't cracked it yet, feel free to have a play, I'll PR the branch (see Nick's affiliation for the issue).

I'm going to get on with the IR stuff for a bit.

**Comment by cclarkson** [comment]
@alimanfoo, I have an ugly workaround that will be fine if you don't get a chance to look at this before tomorrow (pushed it to the [PR](https://github.com/malariagen/ag1000g-phase2-data-paper/pull/238))
